version: '3'
services:
        angular-client:
                build:
                        context: .
                        dockerfile: ./angular-client/Dockerfile
                        restart: always
        express-server:
                build:
                        context: .
                        dockerfile: ./express-server/Dockerfile
                        restart: always
                        ports: '3000:3000'
